In [1]:
import numpy as np

In [3]:
v1 = np.array([10, 6, 7])
v2 = np.array([10, 6, 7])
print(v1)
print(v2)


[10  6  7]
[10  6  7]


In [4]:
v1 = np.array([10, 6, 7])
v1

array([10,  6,  7])

In [5]:
v3 = np.array(5)
v3

array(5)

In [16]:
print(v1.shape)
print(v3.ndim)

(3,)
0


In [24]:
class Student:
    def __init__(self, name, age):
        self._name = name
        self.age = age

    @property
    def name(self):
        return f"{self._name}"

In [26]:
s1 = Student("Faris", 21)
s1.name

'Faris'

In [28]:
vec = np.array([1, 2, 3 ,4, 5, 6])
mat = vec.reshape(2, 3)
print(mat)

[[1 2 3]
 [4 5 6]]


In [31]:
vec = np.array([1, 2, 3 ,4])
vec.shape[0]

4

In [33]:
vec = np.array([1, 2, 3 ,4])
mat = vec.reshape(vec.shape[0], 1)
print(mat)

[[1]
 [2]
 [3]
 [4]]


In [34]:
vec = np.array([1, 2, 3 ,4])
mat = vec[:,None]
print(mat)

[[1]
 [2]
 [3]
 [4]]


In [35]:
def array_reshape(arr, row = -1, cols= -1):
    try:
        arr = np.array(arr)
        return arr.reshape(row, cols)
    except Exception as e:
        raise ValueError(f"Invalid Reshape operation: {e}")

In [36]:
vec = [1, 2, 3 ,4, 5, 6]
print("test 1(2*3 matrix):", array_reshape(vec, 2, 3))

test 1(2*3 matrix): [[1 2 3]
 [4 5 6]]


In [ ]:
#object , string, int, float, bool, complex

In [46]:
class c:
    x = 3
o1 = c()

In [58]:
mat = np.array([[3, 2, 6], 
                [4, 5, True]])
fmat = mat.astype(str)
print(fmat.dtype)

<U21


In [62]:
v = np.array([3, 2, 6, 4, 5])
v[2:5]

array([6, 4, 5])

In [63]:
m = np.array([[3, 2, 6],
              [4, 5, 7],
              [1, 2, 3]])

m[1:3, 0:2]

array([[4, 5],
       [1, 2]])

In [65]:
mat = np.array([[1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9]])
mat_transpose = mat.T
print(mat_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [67]:
mat = np.zeros((3, 3))
mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
mat = np.ones((3, 3))
mat

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
angels = np.arange(0, 91, 15)
angels

array([ 0, 15, 30, 45, 60, 75, 90])

In [76]:
vec = np.linspace(0,10, num = 10)
vec

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [78]:
vec = np.identity(3, dtype = "float")
vec

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
import random
np.random.random((3, 3))

array([[0.48219686, 0.15365983, 0.2265131 ],
       [0.80781024, 0.4314846 , 0.74161613],
       [0.14837173, 0.84836008, 0.95254366]])

In [1]:
import numpy as np

In [ ]:
class Student:
    def __init__(self, name, age):
        self._name = name
        self.age = age

    @property
    def name(self):
        return f"{self._name}"

In [4]:
vec = np.linspace(0, 10, num = 25)
mat = vec.reshape(5, 5)
mat

array([[ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667],
       [ 2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ],
       [ 4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333],
       [ 6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667],
       [ 8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ]])

In [6]:
i = np.identity(3, dtype = "float")
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.random.random((3, 3))

array([[0.33870454, 0.54606288, 0.00324791],
       [0.70095247, 0.23661267, 0.46156879],
       [0.34042258, 0.18234605, 0.0751142 ]])

In [8]:
np.random.randint(0,11,(5,5))

array([[5, 3, 9, 1, 5],
       [6, 4, 3, 7, 9],
       [0, 8, 4, 0, 6],
       [7, 4, 8, 2, 2],
       [2, 6, 8, 5, 2]], dtype=int32)

In [9]:
a = ['Faris', 'doaa', 'omar']
np.random.choice(a, size =(3,4))

array([['omar', 'omar', 'doaa', 'omar'],
       ['doaa', 'doaa', 'doaa', 'doaa'],
       ['Faris', 'Faris', 'Faris', 'Faris']], dtype='<U5')

In [11]:
mat1 = np.ones((3, 4))
mat2 = np.zeros((5, 3))
np.savez("matrices.npz",ones = mat1, zeros = mat2)

In [12]:
with np.load("matrices.npz") as file:
    mat1 = file['ones']
    mat2 = file['zeros']

In [13]:
print(mat1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
print(mat2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
m1 = np.array([[1, 2, 3],
               [0, 0, 0]])

m2 = np.array([[5, 6, 7],
               [1, 1, 1]])

mat3 = np.vstack((m1, m2))
print(mat3)

[[1 2 3]
 [0 0 0]
 [5 6 7]
 [1 1 1]]


In [16]:
m1 = np.array([[1, 2, 3],
               [0, 0, 0]])

m2 = np.array([[5, 6, 7],
               [1, 1, 1]])

mat3 = np.hstack((m1, m2))
print(mat3)

[[1 2 3 5 6 7]
 [0 0 0 1 1 1]]


In [ ]:
class Student:
    def __init__(self, name):
        self._name = name

    def __eq__(self, value:):

In [18]:
s1 = Student("Faris")
s2 = Student("Shahd")
s1 == s2

False

In [20]:
v = np.array([1, 2, 3 ,4, 5, 0])
np.any(v > 3)

np.True_

In [22]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([3, 0, 4, 2, 5])

np.isclose(v1, v2, atol=1)

array([False, False,  True, False,  True])

In [23]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([3, 0, 4, 2, 5])

np.allclose(v1, v2, atol=1)

False

In [24]:
v = np.array([2, 3, 4, 10])
condition = v >= 4
print(condition)

[False False  True  True]


In [25]:
v = np.array([2, 3, 4, 10])
condition = v >= 4
v[condition] = -1
print(v)

[ 2  3 -1 -1]


In [26]:
v = np.array([2, 3, 4, 10])
condition = v >= 4
new_arr = np.where(condition, -1, v)
print(new_arr)

[ 2  3 -1 -1]


In [29]:
v = np.array([1, 2, 3])
c = 2
summation = v + c
multiplication = v * c
print(summation)
print(multiplication)

[3 4 5]
[2 4 6]


In [32]:
mat1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

v1 = np.array([0.5, 0.2, 0.1])
matrix3 = mat1 + v1
print(matrix3)

[[1.5 2.2 3.1]
 [4.5 5.2 6.1]
 [7.5 8.2 9.1]]
