In [1]:
import numpy as np

In [3]:
v1 = np.array([10, 6, 7])
v2 = np.array([10, 6, 7])
print(v1)
print(v2)


[10  6  7]
[10  6  7]


In [4]:
v1 = np.array([10, 6, 7])
v1

array([10,  6,  7])

In [5]:
v3 = np.array(5)
v3

array(5)

In [16]:
print(v1.shape)
print(v3.ndim)

(3,)
0


In [24]:
class Student:
    def __init__(self, name, age):
        self._name = name
        self.age = age

    @property
    def name(self):
        return f"{self._name}"

In [26]:
s1 = Student("Faris", 21)
s1.name

'Faris'

In [28]:
vec = np.array([1, 2, 3 ,4, 5, 6])
mat = vec.reshape(2, 3)
print(mat)

[[1 2 3]
 [4 5 6]]


In [31]:
vec = np.array([1, 2, 3 ,4])
vec.shape[0]

4

In [33]:
vec = np.array([1, 2, 3 ,4])
mat = vec.reshape(vec.shape[0], 1)
print(mat)

[[1]
 [2]
 [3]
 [4]]


In [34]:
vec = np.array([1, 2, 3 ,4])
mat = vec[:,None]
print(mat)

[[1]
 [2]
 [3]
 [4]]


In [35]:
def array_reshape(arr, row = -1, cols= -1):
    try:
        arr = np.array(arr)
        return arr.reshape(row, cols)
    except Exception as e:
        raise ValueError(f"Invalid Reshape operation: {e}")

In [36]:
vec = [1, 2, 3 ,4, 5, 6]
print("test 1(2*3 matrix):", array_reshape(vec, 2, 3))

test 1(2*3 matrix): [[1 2 3]
 [4 5 6]]


In [ ]:
#object , string, int, float, bool, complex

In [46]:
class c:
    x = 3
o1 = c()

In [58]:
mat = np.array([[3, 2, 6], 
                [4, 5, True]])
fmat = mat.astype(str)
print(fmat.dtype)

<U21


In [62]:
v = np.array([3, 2, 6, 4, 5])
v[2:5]

array([6, 4, 5])

In [63]:
m = np.array([[3, 2, 6],
              [4, 5, 7],
              [1, 2, 3]])

m[1:3, 0:2]

array([[4, 5],
       [1, 2]])

In [65]:
mat = np.array([[1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9]])
mat_transpose = mat.T
print(mat_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [67]:
mat = np.zeros((3, 3))
mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
mat = np.ones((3, 3))
mat

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
angels = np.arange(0, 91, 15)
angels

array([ 0, 15, 30, 45, 60, 75, 90])

In [76]:
vec = np.linspace(0,10, num = 10)
vec

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [78]:
vec = np.identity(3, dtype = "float")
vec

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
import random
np.random.random((3, 3))

array([[0.48219686, 0.15365983, 0.2265131 ],
       [0.80781024, 0.4314846 , 0.74161613],
       [0.14837173, 0.84836008, 0.95254366]])